### ISSUE TITLE
Func subcontract not checked

### ISSUE THREAD

**Issue by robnormal** [egonSchiele/contracts.ruby#143]
```ruby
require 'contracts'

module Test
  include Contracts

  Contract None => Func[String => Num]
  def self.nothing
    lambda do; end
  end
end

Test.nothing.()
```

An error should be raised here, but nothing happens.

**Comment by waterlink** [comment]
Yeah, as far as I remember it only wraps proc/lambda/method in delegator when passing params in function (which will be activated on call).

In case of return value wrapping doesn't happen.

Relevant code:

- here happens validation of arguments: https://github.com/egonSchiele/contracts.ruby/blob/master/lib/contracts.rb#L315-L329 and here splat args handling: https://github.com/egonSchiele/contracts.ruby/blob/master/lib/contracts.rb#L331-L363
- here happens obtaining and validation of return value: https://github.com/egonSchiele/contracts.ruby/blob/master/lib/contracts.rb#L367-L382

As you can see in first 2 cases (for arguments) - they are aware of `Contracts::Func` builtin contract and wrap it into `Contract` delegator/wrapper with corresponding contracts contained in `Func` contract.

But in second case (for return value) there is no such thing.

If you want, you can make a PR - should be a trivial change. But don't extract method from this `#call_with` and `#initialize` methods, since they are bottleneck for performance (method calls in Ruby are expensive as it turns out).
