### ISSUE TITLE
Homogeneous generic arrays

### ISSUE THREAD

**Issue by artella-coding** [egonSchiele/contracts.ruby#213]
Is it possible to enforce that generic Arrays should be homogeneous? Currently `ArrayOf[Any]` allows generic arrays to be heterogeneous. e.g.

    include Contracts::Core
    include Contracts::Builtin

    Contract ArrayOf[Any] => nil
    def printLength(arg) 
      print arg.length
    end

    printLength([1,2,"3"])

**Comment by waterlink** [comment]
I think it can be possible, by introducing special built-in contracts as `T`, `K` and `V`. Though they will only work for built-in collection contracts that are aware of them. The code will look like:

```ruby
include Contracts::Core
include Contracts::Builtin

Contract ArrayOf[T] => Num
def len_of(a)
  a.length
end

len_of([1, 2, 3]) # => 3
len_of([1, 2, "3"]) # ContractViolation error
```

This can be done by making `ArrayOf` (and other collection builtin contracts) be aware of `T`, `K` and `V` contracts and treat them a bit special. Actually, simply check that all of the elements are of the same type.

Though, this still **will not allow** something like: `Contract ArrayOf[T] => T`. For the latter to work, contracts engine itself will have to be aware of `T`, `K` and `V`, particularly, function that validates if contract is valid or not for given invocation of the contracted method.

The idea is changing a bit, what is the public interface of the contracts is. Specifically, adding ability for contract to be asked about its `T`, `K` and `V` value after being verified (which makes it mutable, unfortunately, another way would be to return a datastructure, instead of just boolean value). `T`, `K` and `V` will act as `Any`, but will record the type and return it after being matched, which will allow validation function to iterate through all arguments match against single contracts and check, that they all returned same `T`, `K` and `V` (ignoring contracts, that return `Nothing` for one or multiple of `T`, `K` and `V`).

WDYT, @egonSchiele @sfcgeorge @nixpulvis

**Comment by egonSchiele** [comment]
Couldn't you also just write a custom contract for this?

```ruby
Contract (lambda { |a| cls = a[0].class; a.all? { |e| e.class == cls } }) => nil
def print_length args
end
```

**Comment by waterlink** [comment]
That would totally work too, I think.

To make it nicer:

```ruby
class HomogeneousArray
  def self.valid?(array)
    ty = array[0]
    array.all? { e.class == ty } # or  { e.is_a?(ty) }
  end
end
```

and then, just use it like this:

```ruby
Contract HomogeneousArray => nil
def print_length(args)
  # ...
end
```

**Comment by egonSchiele** [comment]
Going to close this, please reopen if needed.

**Comment by artella-coding** [comment]
@waterlink @egonSchiele These two solutions are really awesome! Thank you very much & sorry for the late reply.

p.s. I think `HomogeneousArray` needs to be slightly adjusted to the following : 

     class HomogeneousArray
         def self.valid?(array)
             ty = array[0]
             array.all? {|e| e.class == ty.class } # or  { e.is_a?(ty) }
         end
     end
